### ISSUE TITLE
LoginTest

### ISSUE THREAD

**Issue by LeeHannaa** [LikeLionHGU/GloBuddy-Front#1]
- [x] 구글 로그인 테스트
- [x] 도메인 한정 로그인 시도
- [x] 유저 정보 확인
- [x] url 직접 접근 제한
- [x] 로그아웃 기능 (로그아웃 시 유저 정보 삭제)

**Comment by HAEOII** [comment]
구글 api id가 없어서 임의로 (정섭멘토님이) 전에 작업했던 client id 가져와서 로그인 후에 프로필 입력 절차 확인해봤어요! 마지막 회원정보 화면에서 사진 업로드 후에 이미지가 안 나와요ㅛ
